name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Microservices Images
        run: |
          docker build -t api-gateway-img:latest ./api-gateway
          docker build -t order-service-img:latest ./order-service
          docker build -t product-service-img:latest ./product-service

      - name: Verify Builds
        run: docker images